doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': 'C:\Users\Hippolyte\Desktop\ProjetL3\projet'
    enable_profiler: false
